"""Integration checks against the deliverables generated by `uv run lab6-ds`."""

import json
from pathlib import Path
import unittest

import networkx as nx
import numpy as np
import pandas as pd

from lab6_ds.analysis import MODEL_REVISION


class ExportTests(unittest.TestCase):
    def test_graph_and_projection_exports(self):
        nodes = pd.read_csv("results/nodes.csv")
        edges = pd.read_csv("results/edges.csv")
        graph = nx.from_pandas_edgelist(edges, edge_attr="weight")
        self.assertEqual((len(nodes), len(edges), edges.weight.sum()), (351, 343, 406))
        self.assertEqual(set(nodes.node_id), set(graph))
        self.assertTrue(nx.is_bipartite(graph))
        self.assertEqual(nx.number_connected_components(graph), 10)
        for name in ("author", "video"):
            projection = pd.read_csv(f"results/{name}_projection_edges.csv")
            for row in projection.itertuples():
                self.assertEqual(row.weight, len(set(graph[row.source]) & set(graph[row.target])))
        coverage = pd.read_csv("results/video_coverage.csv")
        self.assertEqual((len(coverage), coverage.in_observed_network.sum()), (293, 19))

    def test_originals_sentiment_and_scope(self):
        raw = pd.read_csv("youtube_comments.csv", encoding="utf-8-sig", skipinitialspace=True)
        raw.columns = raw.columns.str.strip()
        comments = pd.read_csv("results/comments_sentiment.csv", keep_default_na=False)
        self.assertEqual(comments.texto_original.tolist(), raw.text.tolist())
        self.assertEqual(len(comments), 406)
        self.assertTrue(comments.comment_id.is_unique)
        self.assertTrue(comments.model_revision.eq(MODEL_REVISION).all())
        self.assertTrue(comments.sentiment_status.eq("classified").all())
        probabilities = comments[["p_NEG", "p_NEU", "p_POS"]].astype(float)
        self.assertTrue(np.allclose(probabilities.sum(axis=1), 1, atol=1e-6))
        self.assertEqual(probabilities.idxmax(axis=1).str.removeprefix("p_").tolist(), comments.sentiment.tolist())
        profiles = pd.read_csv("results/community_profiles.csv")
        self.assertEqual(profiles.internal_comments.sum(), comments.internal.sum())
        self.assertEqual(profiles.incoming_comments.sum(), (~comments.internal).sum())
        self.assertEqual(profiles.outgoing_comments.sum(), (~comments.internal).sum())
        self.assertEqual(profiles.head(3).internal_comments.tolist(), [158, 48, 34])
        manifest = json.loads(Path("results/manifest.json").read_text())
        self.assertEqual(manifest["validation"]["classified"], 406)
        print("Verified sentiment:", comments.sentiment.value_counts().to_dict(),
              "truncated:", int(comments.truncated.sum()), "low confidence:", int(comments.low_confidence.sum()))


if __name__ == "__main__":
    unittest.main()
